### ISSUE TITLE
algebra documentation

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [aldorlang/aldor#135]
The original algebra documentation from
https://www-sop.inria.fr/cafe/Manuel.Bronstein/algebra/
isn't available anymore, Manuel Bronstein died in 2005 
https://www.researchgate.net/publication/220203836_In_memory_of_Manuel_Bronstein
the only way to have it seems to build it from source

**Comment by nsajko** [comment]
Pardon me, but how does one build the algebra documentation? I see there are some Tex files [in the tree](https://github.com/pippijn/aldor/tree/master/aldor/lib/algebra/doc/tex), but there is no Makefile or instructions there, even though it seems a relevant Makefile is referenced in the README file in that directory.

**Comment by hemmecke** [comment]
The only thing I know is that the data in the .as files were done for
usage with ALDOC. You find something inside aldor/lib/aldor/doc/tex. But
how exactly it is build I don't know or cannot easily recall.

What exactly do you want to know about this library?

**Comment by nsajko** [comment]
> What exactly do you want to know about this library?

I had an idea to solve a simple mathematical problem in a couple different languages: https://github.com/nsajko/discrete-math-lab1

Aldor was one of the intended targets, and AFAIK algebra is the "math" library for Aldor, so I am mainly interested just in its possible ability to solve linear equations. But, hypothetically, I may want to use Aldor more later, so I would need to know what I can use it and its algebra library for.

**Comment by pbroadbery** [comment]
I removed the original makefiles that created the documentation.  Obviously
I had intended to restore the functionality later...
I'll do that now & upload the pdf files to github

The commit in question was a2d745b8, I'm forward porting it, although it
has to be said that my latex is a bit rusty.

Peter

**Comment by hemmecke** [comment]
> The commit in question was a2d745b8, I'm forward porting it, although it
> has to be said that my latex is a bit rusty.

I guess I can help with the latex part. However, time is an issue.

Ralf

**Comment by pbroadbery** [comment]
OK - it wasn't as painful as expected.  PDF files attached here.  I'll create a PR for the build changes in a day or two.

- Allesandro, these will cover the current library, hope they are good enough for what you need.
If not, don't hesitate to ask for more details.
[libaldor.pdf](https://github.com/pippijn/aldor/files/5469931/libaldor.pdf)
[algebra.pdf](https://github.com/pippijn/aldor/files/5469932/algebra.pdf)

**Comment by LdBeth** [comment]
It might be a good idea to upload EPS version for FIG format graphics so one does not need extra `fig2eps` installed to compile the LaTeX documentation.

**Comment by pbroadbery** [comment]
I've created a branch containing a working documentation build - #144 (pab/gmp-doc-fixes).  You will need to specify '--enable-documentation' at configure time, and have the necessary prerequisites installed.
If you have time to test please do. I will do some further tests on the gmp side of the patch & merge into master unless any problems are found.

**Comment by pbroadbery** [comment]
Closed as doc now builds
